#!/usr/bin/env python3
"""Anchor-drift sweep: find all relative-time queries in golden set."""

import yaml
import re
from pathlib import Path

# Relative time patterns that drift with eval date
_DRIFT_PATTERNS = [
    r"最近",
    r"近期",
    r"近日",
    r"上周",
    r"上.*周",
    r"上个?月",
    r"上月",
    r"这周",
    r"本周",
    r"这个?月",
    r"本月",
    r"今天",
    r"昨天",
    r"前天",
    r"明天",
    r"后天",
    r"前几天",
    r"前段时间",
]

_COMPILED = [re.compile(p) for p in _DRIFT_PATTERNS]


def is_relative_time(query: str) -> tuple[bool, str | None]:
    for pat in _COMPILED:
        if pat.search(query):
            return True, pat.pattern
    return False, None


def main() -> None:
    gq_path = Path("tools/eval/golden_queries.yaml")
    data = yaml.safe_load(open(gq_path, "r", encoding="utf-8"))

    matches = []
    for q in data["queries"]:
        if q.get("skip"):
            continue
        query_text = q.get("query", "")
        rel, matched_pat = is_relative_time(query_text)
        if rel:
            matches.append(
                {
                    "id": q.get("id"),
                    "query": query_text,
                    "pattern": matched_pat,
                    "audit_note": q.get("audit_note"),
                    "category": q.get("category"),
                }
            )

    # Output report
    print("# Anchor-Drift Sweep Report")
    print(f"\nTotal active queries scanned: {sum(1 for q in data['queries'] if not q.get('skip'))}")
    print(f"Relative-time queries found: {len(matches)}\n")

    print("| ID | Query | Pattern | Audit Note | Status |")
    print("|----|-------|---------|------------|--------|")

    already_flagged = 0
    need_flag = 0
    for m in matches:
        note = m["audit_note"] or ""
        if "anchor_drift" in note.lower() or "relative_time" in note.lower():
            status = "[OK] Already flagged"
            already_flagged += 1
        else:
            status = "[NEED] NEEDS FLAG"
            need_flag += 1
        print(f"| {m['id']} | {m['query']} | `{m['pattern']}` | {note or '-'} | {status} |")

    print(f"\nSummary: {already_flagged} already flagged, {need_flag} need flag.")

    # Save report
    report_path = Path("tools/dev/anchor-drift-sweep.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("# Anchor-Drift Sweep Report\n\n")
        f.write("> Generated by `tools/dev/anchor_drift_sweep.py`\n\n")
        f.write(f"- Total active queries: {sum(1 for q in data['queries'] if not q.get('skip'))}\n")
        f.write(f"- Relative-time queries found: **{len(matches)}**\n\n")
        f.write("| ID | Query | Pattern | Category | Audit Note | Action |\n")
        f.write("|----|-------|---------|----------|------------|--------|\n")
        for m in matches:
            note = m["audit_note"] or ""
            if "anchor_drift" in note.lower() or "relative_time" in note.lower():
                action = "Keep flagged"
            else:
                action = "ADD `relative_time_anchor_drift`"
            line = (
                f"| {m['id']} | {m['query']} | `{m['pattern']}` |"
                f" {m['category']} | {note or '-'} | {action} |\n"
            )
            f.write(line)

        f.write("\n## Analysis\n\n")
        for m in matches:
            note = m["audit_note"] or ""
            if "anchor_drift" in note.lower() or "relative_time" in note.lower():
                continue
            f.write(f"### {m['id']}: {m['query']}\n")
            f.write(f"- **Pattern**: `{m['pattern']}`\n")
            f.write(f"- **Category**: {m['category']}\n")
            pattern_clean = m["pattern"].replace(".*", "").replace("?", "")
            f.write(
                "- **Why it drifts**: The interpretation of "
                f"'{pattern_clean}' depends on `date.today()`,"
            )
            f.write(" which changes between eval runs.\n")
            f.write("- **Action**: Add `audit_note: relative_time_anchor_drift`\n\n")

    print(f"\nReport saved to {report_path}")


if __name__ == "__main__":
    main()
